### ISSUE TITLE
Add file tab completion for setsrc and setdest commands.

### ISSUE THREAD

**Issue by dscalzi** [dscalzi/ZipExtractor#1]
The `setsrc` and `setdest` commands should have tab completers for quickly typing file paths. This should support both relative and absolute paths.

**Comment by randombyte-developer** [comment]
Sponge supports tab completing of custom types. To use that, you would have to use the Sponge Commands structure though: https://docs.spongepowered.org/stable/en/plugin/commands/index.html

**Comment by dscalzi** [comment]
I already have that implemented for basic completions. What I'm referring to is the type of file path completion you would get in a bash shell.
